# Site Settings #
title: "Siena Guerrero"
name: "Siena Maria Guerrero"
location: "Los Angeles"
slogan: "Tech Enthusiast, Software Engineer"
callout: "Currently looking for research or cs-related internships in Summer 2020."

# Use a maximum of 150 characters for SEO-purposes.
description:
  Personal website for Siena Guerrero. Digital designer, tinkerer, and lover of coding. Software Engineer at Swoop, former Computer Science Major at Harvey Mudd College.`

  # Main author of the website
author: sienaguerrero
email: hello@sienaguerrero.com

# Social media links
socialMedia:
  instagram: sienaguerrero
  linkedin: sienaguerrero
  github: sienaguerrero

# 'Many Thanks' section in footer
manyThanks:
  - item:
      - text: "Favicons by Teresa Ibarra"
      - url: "http://teresaibarra.github.io/"

  - item:
      - text: "Personal Icon by Lydia Amora"
      - url: "https://twitter.com/lydiaamora"
