# Site Settings #
title: "Siena Maria Guerrero"
slogan: "Tech Enthusiast, Software Engineer"

# Use a maximum of 150 characters for SEO-purposes.
description: "Personal website for Siena Guerrero. Digital designer, tinkerer, and lover of coding. Current Software Engineer at Swoop, former Computer Science Major at Harvey Mudd College."
credits: '<p>Created with &hearts; by <a href="sienaguerrero.github.io">sienaguerrero</a> with <a href="https://www.gatsbyjs.com/" target="_blank">Gatsby</a> using <a href="https://mui.com/">MUI</a>.</p>'

# Main author of the website
author: sienaguerrero

# 'About This Site' and site hosting information in footer
about-this-site: Personal website for Siena Guerrero. Digital designer, tinkerer, and lover of coding. Computer Science Major at Harvey Mudd College. Learn more about my story.
hosting-description: Hosted on Github Pages, maintained on Github. If you find an error on this site, let me know by submitting an issue.

# 'Many Thanks' section in footer
many-thanks:
  - item:
      - name: "Favicons by my friend, Teresa Ibarra"
      - url: "http://teresaibarra.github.io/"
      - class: "network-favicon"
      - title: "Favicons by Teresa Ibarra"
  - item:
      - name: "Personal Icon by Lydia Amora"
      - url: "https://twitter.com/lydiaamora"
      - class: "image-icon"
      - title: "Personal Icon by Lydia Amora"
